[world]
width = 50
hight = 20


[entity.herbivore]
hp = 100
speed = 3
visual_radius = 10
nutritional_quality = 40

[entity.grass]
nutritional_quality = 15

[entity.predator]
hp = 100
speed = 2
visual_radius = 10
power = 50


[spawn.init]
predator = 10
herbivore = 10
tree = 10
grass = 10
rock = 10


[spawn.interval.herbivore]
interval = 3
count = 2


[spawn.interval.grass]
interval = 2
count = 3

[spawn.interval.predator]
interval = 3
count = 2

[starve]
power = 10

[icon]
predator = "ğŸ¯"
herbivore = "ğŸ¦“"
rock = "ğŸª¨"
grass = "ğŸŒ±"
tree = "ğŸŒ³"
default = "ğŸŸ«"
